[package]
name = "data_orchestra"
version = "0.1.0"
edition = "2021"

[dependencies]
# Logger
log = "0.4"
env_logger = "0.11.7"

# Console argument parser
clap = { version = "4.5.37", features = ["derive"] }

# HTTP(s) request
reqwest = { version = "0.12", features = ["json"] }

# Async
tokio = { version = "1", features = ["full"] }

# Json parser
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"

# Yaml parser
yaml-rust = "0.4"

# Ssh library
ssh2 = "0.9.5"

# CMD colors
ansi_term = "0.12.1"

# Dir traverser
walkdir = "2.5.0"

[dev-dependencies]
rstest = "0.25.0"
