[package]
name = "data_orchestra_master"
authors = ["Mathieu Groenen", "David Lengweiler"]
license = "Apache-2.0"

version = "0.1.0"
edition = "2024"

[profile.release]
debug = true

[dependencies]
# Logger
log = "0.4"

# Console argument parser
clap = { version = "4.5.37", features = ["derive", "env"] }

# HTTP(s) request
reqwest = { version = "0.12", features = ["json"] }

# Async
tokio = { version = "1", features = ["full"] }

# Json parser
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"

# Ssh library
ssh2 = "0.9.5"

actix-web = "4"
actix-cors = "0.7.1"

derive_builder = "0.20.2"

tracing = "0.1"
tracing-subscriber = "0.3"
tracing-appender = "0.2"

data_orchestra_engine = { path = "../engine" }
data_orchestra_parser = { path = "../parser" }

toml = "0.9.7"
