[package]
name = "data_orchestra_agent"
authors = ["Mathieu Groenen", "David Lengweiler"]
license = "Apache-2.0"

version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
actix-cors = "0.7.1"

tokio = { version = "1", features = ["full"] }
log = "0.4.27"

tracing = "0.1"
tracing-subscriber = "0.3"
tracing-appender = "0.2"

serde = { version = "1.0.228", features = ["derive"] }

# HTTP(s) request
reqwest = { version = "0.12", features = ["json"] }

