name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-main:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build main
      run: cargo build --verbose
    - name: Build kafka producer attachable
      run: |
        cd services/attachables/kafka_producer
        cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
      
  build-services:
  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build API
        run: |
          cd services/api
          cargo build --verbose

      - name: Build Kafka Producer attachable
        run: |
          cd services/attachables/kafka_producer
          cargo run --verbose

      - name: Build Kafka Consumer attachable
        run: |
          cd services/attachables/kafka_consumer
          cargo run --verbose
      
